export enum Types {
    Normal = "Normal", 
    Water = "Water",
    Fire = "Fire", 
    Grass = "Grass",
    Electric = "Electric",
    Ice = "Ice",
    Fighting = "Fighting",
    Dark = "Dark",
    Psychic = "Psychic",
    Bug = "Bug",
    Rock = "Rock",
    Ground = "Ground",
    Flying = "Flying",
    Dragon = "Dragon", 
    Ghost = "Ghost",
    Poison = "Poison",
    Fairy = "Fairy",
    Steel = "Steel"
}